# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Build for $(buildConfiguration)'
  inputs:
    command: build
    arguments: -c $(buildConfiguration)
    includesource: true
    includesymbols: true
  
# - script: dotnet test --configuration $(buildConfiguration) --no-build
#   displayName: 'dotnet test $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Test for $(buildConfiguration)'
  inputs:
    command: test
    nobuild: true
    arguments: -c $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Create nuget package for version $(Package Version)'
  inputs:
    command: pack
    packagesToPack: 'src/prismicio.AspNetCore/prismicio.AspNetCore.csproj'
    arguments: -c $(buildConfiguration) --version-suffix "-alpha-$(Build.BuildNumber)"
    nobuild: true
    includesymbols: true
    includesource: true
    outputDir: $(Build.ArtifactStagingDirectory)/packages
    zipAfterPublish: true

# - task: NuGetCommand@2
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'NuGet.org'