# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet clean
  displayName: 'Clean Build Directories'

- task: DotNetCoreCLI@2
  displayName: 'Build for $(buildConfiguration)'
  inputs:
    command: build
    arguments: -c $(buildConfiguration)
    includesource: true
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'Test for $(buildConfiguration)'
  inputs:
    command: test
    arguments: -c $(buildConfiguration) --no-build  /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: custom
    custom: pack
    arguments: src/prismicio.AspNetCore/prismicio.AspNetCore.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/packages -v m --no-build --include-symbols
    zipAfterPublish: true

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg;!$(Build.ArtifactStagingDirectory)/packages/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'