# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:-r)

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildRevision: -$[$(date:yyyyMMdd)$(rev:-r)]

steps:

- script: dotnet clean
  displayName: 'Clean Build Directories'

# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Build for $(buildConfiguration)'
  inputs:
    command: build
    arguments: -c $(buildConfiguration)
    includesource: true
    includesymbols: true
  
# - script: dotnet test --configuration $(buildConfiguration) --no-build
#   displayName: 'dotnet test $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Test for $(buildConfiguration)'
  inputs:
    command: test
    nobuild: true
    arguments: -c $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: custom
    custom: pack
    arguments: src/prismicio.AspNetCore/prismicio.AspNetCore.csproj --version-suffix alpha-$(buildRevision) -v m
    nobuild: true
    includesymbols: true
    includesource: true
    outputDir: $(Build.ArtifactStagingDirectory)/packages
    zipAfterPublish: true

# - task: NuGetCommand@2
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg;!$(Build.ArtifactStagingDirectory)/packages/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'NuGet.org'